name: Test SSH to VPS
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH ping
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            set -euxo pipefail
            whoami
            hostname -I
            docker --version
            docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
